---
title: "Creating Windows"
author: "Ryan Arias Delafosse"
date: "2/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Creating Windows

This is the file to show how the windows of three years were created for the purposes of looking at change over time.

The current links are LOCAL to Ryan's computer, so it's probably a good idea to make them URL links later.

## Load Libraries

```{r load libraries}
# Load library
library(dplyr)
library(data.table)
library(readr)
library(ggplot2)
```

## Import Merged Dataset

```{r Import Merged Dataset, echo=FALSE}

# Get a List of all files in directory named with a keyword, say all `.csv` files

library(readr)
merged <- read_delim("Data/merged.csv", 
    "\t", escape_double = FALSE, col_types = cols(image_id = col_number(), 
        latitude = col_number(), longitude = col_number()), 
    trim_ws = TRUE)

```


## Reviewing Data

```{r testing merged data}
summary(merged)
str(merged)
skimr::skim(merged)
```

## Filtering Data


```{r 2007 filter users}
## User must appear more than once
merged <- merged%>%
                      group_by(owner_id) %>%
                      filter(n()>2)%>%
                      arrange(owner_id,date_taken)
```

```{r filter by time}
merged$Date <- as.Date(merged$date_taken) 

```

```{r create paths and windows by years}
# 
data_2007to2009 <- merged %>%
                        filter(Date >= as.Date('2007-01-01') & Date <= as.Date('2009-12-31'))

data_2010to2012 <- merged %>%
                        filter(Date >= as.Date('2010-01-01') & Date <= as.Date('2012-12-31'))

data_2013to2015 <- merged %>%
                        filter(Date >= as.Date('2013-01-01') & Date <= as.Date('2015-12-31'))

data_2016to2018 <- merged %>%
                        filter(Date >= as.Date('2016-01-01') & Date <= as.Date('2018-12-31'))
```


## Trying to map

```{r 2007 map}
# Load libraries
library(rworldmap)
library(ggmap)
register_google(key = "AIzaSyA5RyFB0KqjBQZ2o-uOUcGYK8jjb4v9eYM")
google_key()
ggmap_show_api_key()

# Map Bordeaux
map <- get_map(location = 'Bordeaux', zoom = 15)

# Plot data points
ggmap(map) +
  geom_point(
    aes(x = data_2016to2018$longitude, y = data_2016to2018$latitude),
    data = data_2016to2018, alpha = .5
    )
```


## Clustering

```{r clustering 2007}
library(dbscan)
dbs_merged <- dbscan(data_2016to2018[,3:4], eps = 0.000055, minPts = 80)
data_2016to2018$cluster <- dbs_merged$cluster

summary(dbs_merged)
str(dbs_merged)
```



## Mapping Clusters

```{r}
groups  <- data_2016to2018 %>% filter(cluster != 0)
noise  <- data_2016to2018 %>% filter(cluster == 0)


ggplot(data_2016to2018, aes(x = longitude, y = latitude, alpha = 0.5)) + 
  geom_point(aes(fill = "grey"), noise) +
  geom_point(aes(colour = as.factor(cluster)), groups,
             size = 3)
```

